### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by ric2016** [ric2016/gov4webtrees#13]
May have to be fixed in 2.x as well.

https://www.webtrees.net/media/kunena/attachments/6953/error.txt

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry &#039;136-eng&#039; for key &#039;PRIMARY&#039; (SQL: insert into `gov_descriptions` (`type`, `lang`, `description`) values (136, eng, commune)) â€¦/vendor/illuminate/database/Connection.php:664 #0 â€¦/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection-&gt;runQueryCallback(&#039;insert into `go...&#039;, Array, Object(Closure)) #1 â€¦/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection-&gt;run(&#039;insert into `go...&#039;, Array, Object(Closure)) #2 â€¦/vendor/illuminate/database/Connection.php(411): Illuminate\Database\Connection-&gt;statement(&#039;insert into `go...&#039;, Array) #3 â€¦/vendor/illuminate/database/Query/Builder.php(2646): Illuminate\Database\Connection-&gt;insert(&#039;insert into `go...&#039;, Array) <b>#4 â€¦/modules_v4/vesta_gov4webtrees/FunctionsGov.php(461):`

**Comment by ric2016** [comment]
This is a 2.x issue only.
